frr version 10.0
frr defaults traditional
hostname r3
!
interface eth1
 ip address 10.0.3.2/30
!
interface eth2
 ip address 10.2.3.2/30
!
interface eth3
 ip address 10.3.4.1/30
!
interface eth4
 ip address 192.168.6.1/24
!
router ospf
 network 10.0.3.0/30 area 0
 network 10.2.3.0/30 area 0
 network 10.3.4.0/30 area 0
 network 192.168.6.0/24 area 0
!
router rip
 version 2
 network 10.0.3.0/30
 network 10.2.3.0/30
 network 10.3.4.0/30
 network 192.168.6.0/24
 no auto-summary
!
line vty
!
