frr version 10.0
frr defaults traditional
hostname r0
!
! Configuração de Interfaces (comum a todos os protocolos)
interface eth1
 ip address 10.0.1.1/30
!
interface eth2
 ip address 10.0.3.1/30
!
interface eth3
 ip address 192.168.5.1/24
!
! Bloco OSPF (só é carregado se ospfd=yes)
router ospf
 network 10.0.1.0/30 area 0
 network 10.0.3.0/30 area 0
 network 192.168.5.0/24 area 0
!
! Bloco RIP (só é carregado se ripd=yes)
router rip
 version 2
 network 10.0.1.0/30
 network 10.0.3.0/30
 network 192.168.5.0/24
 no auto-summary
!
line vty
!
